In [2]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from keras.optimizers import Adam
import numpy as np
import pandas as pd

In [11]:
dataset = load_iris()

features = dataset.data
targets = np.array(dataset.target).reshape(-1 , 1)

encoder = OneHotEncoder(sparse = False)
targets = encoder.fit_transform(targets)

print(targets)

model = Sequential()

model.add(Dense(10 , input_dim = 4 , activation = 'relu'))
model.add(Dense(10 , input_dim = 10 , activation = 'relu'))
model.add(Dense(10 , input_dim = 10 , activation = 'relu'))
model.add(Dense(3 , activation = 'softmax'))

feature_train , feature_test , target_train , target_test = train_test_split(features , targets , test_size = 0.2 , random_state =None)

optimizer = Adam(learning_rate = 0.001)

model.compile(loss = 'categorical_crossentropy' , optimizer = optimizer , metrics = ['accuracy'])

model.fit(feature_train , target_train , epochs = 1000 , verbose = 2)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

Epoch 81/1000
4/4 - 0s - loss: 0.2520 - accuracy: 0.9667 - 11ms/epoch - 3ms/step
Epoch 82/1000
4/4 - 0s - loss: 0.2469 - accuracy: 0.9667 - 13ms/epoch - 3ms/step
Epoch 83/1000
4/4 - 0s - loss: 0.2410 - accuracy: 0.9750 - 12ms/epoch - 3ms/step
Epoch 84/1000
4/4 - 0s - loss: 0.2368 - accuracy: 0.9667 - 11ms/epoch - 3ms/step
Epoch 85/1000
4/4 - 0s - loss: 0.2317 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 86/1000
4/4 - 0s - loss: 0.2265 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 87/1000
4/4 - 0s - loss: 0.2232 - accuracy: 0.9667 - 12ms/epoch - 3ms/step
Epoch 88/1000
4/4 - 0s - loss: 0.2174 - accuracy: 0.9667 - 10ms/epoch - 3ms/step
Epoch 89/1000
4/4 - 0s - loss: 0.2131 - accuracy: 0.9750 - 6ms/epoch - 1ms/step
Epoch 90/1000
4/4 - 0s - loss: 0.2088 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 91/1000
4/4 - 0s - loss: 0.2053 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 92/1000
4/4 - 0s - loss: 0.2029 - accuracy: 0.9667 - 10ms/epoch - 3ms/step
Epoch 93/1000
4/4 - 0s - loss: 0

Epoch 182/1000
4/4 - 0s - loss: 0.0884 - accuracy: 0.9750 - 14ms/epoch - 3ms/step
Epoch 183/1000
4/4 - 0s - loss: 0.0873 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 184/1000
4/4 - 0s - loss: 0.0864 - accuracy: 0.9667 - 7ms/epoch - 2ms/step
Epoch 185/1000
4/4 - 0s - loss: 0.0853 - accuracy: 0.9750 - 10ms/epoch - 3ms/step
Epoch 186/1000
4/4 - 0s - loss: 0.0857 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 187/1000
4/4 - 0s - loss: 0.0865 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 188/1000
4/4 - 0s - loss: 0.0852 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 189/1000
4/4 - 0s - loss: 0.0839 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 190/1000
4/4 - 0s - loss: 0.0839 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 191/1000
4/4 - 0s - loss: 0.0829 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 192/1000
4/4 - 0s - loss: 0.0888 - accuracy: 0.9417 - 9ms/epoch - 2ms/step
Epoch 193/1000
4/4 - 0s - loss: 0.0812 - accuracy: 0.9750 - 10ms/epoch - 2ms/step
Epoch 194/1000
4/4 - 0s 

Epoch 283/1000
4/4 - 0s - loss: 0.0708 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 284/1000
4/4 - 0s - loss: 0.0694 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 285/1000
4/4 - 0s - loss: 0.0717 - accuracy: 0.9667 - 10ms/epoch - 2ms/step
Epoch 286/1000
4/4 - 0s - loss: 0.0691 - accuracy: 0.9667 - 7ms/epoch - 2ms/step
Epoch 287/1000
4/4 - 0s - loss: 0.0694 - accuracy: 0.9750 - 10ms/epoch - 3ms/step
Epoch 288/1000
4/4 - 0s - loss: 0.0707 - accuracy: 0.9750 - 10ms/epoch - 3ms/step
Epoch 289/1000
4/4 - 0s - loss: 0.0691 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 290/1000
4/4 - 0s - loss: 0.0686 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 291/1000
4/4 - 0s - loss: 0.0687 - accuracy: 0.9750 - 13ms/epoch - 3ms/step
Epoch 292/1000
4/4 - 0s - loss: 0.0681 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 293/1000
4/4 - 0s - loss: 0.0689 - accuracy: 0.9667 - 6ms/epoch - 1ms/step
Epoch 294/1000
4/4 - 0s - loss: 0.0690 - accuracy: 0.9667 - 8ms/epoch - 2ms/step
Epoch 295/1000
4/4 - 0s 

Epoch 384/1000
4/4 - 0s - loss: 0.0626 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 385/1000
4/4 - 0s - loss: 0.0635 - accuracy: 0.9750 - 10ms/epoch - 3ms/step
Epoch 386/1000
4/4 - 0s - loss: 0.0624 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 387/1000
4/4 - 0s - loss: 0.0620 - accuracy: 0.9750 - 6ms/epoch - 1ms/step
Epoch 388/1000
4/4 - 0s - loss: 0.0613 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 389/1000
4/4 - 0s - loss: 0.0627 - accuracy: 0.9750 - 10ms/epoch - 3ms/step
Epoch 390/1000
4/4 - 0s - loss: 0.0634 - accuracy: 0.9667 - 7ms/epoch - 2ms/step
Epoch 391/1000
4/4 - 0s - loss: 0.0618 - accuracy: 0.9750 - 10ms/epoch - 2ms/step
Epoch 392/1000
4/4 - 0s - loss: 0.0625 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 393/1000
4/4 - 0s - loss: 0.0620 - accuracy: 0.9750 - 6ms/epoch - 1ms/step
Epoch 394/1000
4/4 - 0s - loss: 0.0627 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 395/1000
4/4 - 0s - loss: 0.0629 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 396/1000
4/4 - 0

Epoch 485/1000
4/4 - 0s - loss: 0.0585 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 486/1000
4/4 - 0s - loss: 0.0582 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 487/1000
4/4 - 0s - loss: 0.0591 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 488/1000
4/4 - 0s - loss: 0.0584 - accuracy: 0.9750 - 12ms/epoch - 3ms/step
Epoch 489/1000
4/4 - 0s - loss: 0.0620 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 490/1000
4/4 - 0s - loss: 0.0592 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 491/1000
4/4 - 0s - loss: 0.0578 - accuracy: 0.9750 - 11ms/epoch - 3ms/step
Epoch 492/1000
4/4 - 0s - loss: 0.0575 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 493/1000
4/4 - 0s - loss: 0.0593 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 494/1000
4/4 - 0s - loss: 0.0573 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 495/1000
4/4 - 0s - loss: 0.0593 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 496/1000
4/4 - 0s - loss: 0.0587 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 497/1000
4/4 - 0s -

Epoch 586/1000
4/4 - 0s - loss: 0.0562 - accuracy: 0.9833 - 16ms/epoch - 4ms/step
Epoch 587/1000
4/4 - 0s - loss: 0.0553 - accuracy: 0.9833 - 13ms/epoch - 3ms/step
Epoch 588/1000
4/4 - 0s - loss: 0.0544 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 589/1000
4/4 - 0s - loss: 0.0549 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 590/1000
4/4 - 0s - loss: 0.0572 - accuracy: 0.9833 - 13ms/epoch - 3ms/step
Epoch 591/1000
4/4 - 0s - loss: 0.0561 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 592/1000
4/4 - 0s - loss: 0.0553 - accuracy: 0.9833 - 10ms/epoch - 2ms/step
Epoch 593/1000
4/4 - 0s - loss: 0.0551 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 594/1000
4/4 - 0s - loss: 0.0569 - accuracy: 0.9750 - 6ms/epoch - 1ms/step
Epoch 595/1000
4/4 - 0s - loss: 0.0562 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 596/1000
4/4 - 0s - loss: 0.0591 - accuracy: 0.9750 - 9ms/epoch - 2ms/step
Epoch 597/1000
4/4 - 0s - loss: 0.0565 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 598/1000
4/4 - 0

Epoch 687/1000
4/4 - 0s - loss: 0.0538 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 688/1000
4/4 - 0s - loss: 0.0559 - accuracy: 0.9833 - 10ms/epoch - 2ms/step
Epoch 689/1000
4/4 - 0s - loss: 0.0531 - accuracy: 0.9833 - 11ms/epoch - 3ms/step
Epoch 690/1000
4/4 - 0s - loss: 0.0532 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 691/1000
4/4 - 0s - loss: 0.0563 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 692/1000
4/4 - 0s - loss: 0.0557 - accuracy: 0.9750 - 8ms/epoch - 2ms/step
Epoch 693/1000
4/4 - 0s - loss: 0.0526 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 694/1000
4/4 - 0s - loss: 0.0548 - accuracy: 0.9833 - 10ms/epoch - 2ms/step
Epoch 695/1000
4/4 - 0s - loss: 0.0538 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 696/1000
4/4 - 0s - loss: 0.0568 - accuracy: 0.9750 - 7ms/epoch - 2ms/step
Epoch 697/1000
4/4 - 0s - loss: 0.0539 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 698/1000
4/4 - 0s - loss: 0.0535 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 699/1000
4/4 - 

Epoch 788/1000
4/4 - 0s - loss: 0.0578 - accuracy: 0.9750 - 22ms/epoch - 5ms/step
Epoch 789/1000
4/4 - 0s - loss: 0.0579 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 790/1000
4/4 - 0s - loss: 0.0522 - accuracy: 0.9833 - 20ms/epoch - 5ms/step
Epoch 791/1000
4/4 - 0s - loss: 0.0524 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 792/1000
4/4 - 0s - loss: 0.0521 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 793/1000
4/4 - 0s - loss: 0.0522 - accuracy: 0.9833 - 20ms/epoch - 5ms/step
Epoch 794/1000
4/4 - 0s - loss: 0.0523 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 795/1000
4/4 - 0s - loss: 0.0516 - accuracy: 0.9833 - 11ms/epoch - 3ms/step
Epoch 796/1000
4/4 - 0s - loss: 0.0527 - accuracy: 0.9833 - 6ms/epoch - 1ms/step
Epoch 797/1000
4/4 - 0s - loss: 0.0534 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 798/1000
4/4 - 0s - loss: 0.0518 - accuracy: 0.9833 - 12ms/epoch - 3ms/step
Epoch 799/1000
4/4 - 0s - loss: 0.0517 - accuracy: 0.9833 - 14ms/epoch - 4ms/step
Epoch 800/1000
4/4

Epoch 889/1000
4/4 - 0s - loss: 0.0503 - accuracy: 0.9833 - 11ms/epoch - 3ms/step
Epoch 890/1000
4/4 - 0s - loss: 0.0503 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 891/1000
4/4 - 0s - loss: 0.0509 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 892/1000
4/4 - 0s - loss: 0.0505 - accuracy: 0.9833 - 6ms/epoch - 2ms/step
Epoch 893/1000
4/4 - 0s - loss: 0.0502 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 894/1000
4/4 - 0s - loss: 0.0503 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 895/1000
4/4 - 0s - loss: 0.0510 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 896/1000
4/4 - 0s - loss: 0.0513 - accuracy: 0.9833 - 10ms/epoch - 3ms/step
Epoch 897/1000
4/4 - 0s - loss: 0.0511 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 898/1000
4/4 - 0s - loss: 0.0520 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 899/1000
4/4 - 0s - loss: 0.0510 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 900/1000
4/4 - 0s - loss: 0.0506 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 901/1000
4/4 - 0s -

Epoch 990/1000
4/4 - 0s - loss: 0.0496 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 991/1000
4/4 - 0s - loss: 0.0502 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 992/1000
4/4 - 0s - loss: 0.0501 - accuracy: 0.9833 - 11ms/epoch - 3ms/step
Epoch 993/1000
4/4 - 0s - loss: 0.0520 - accuracy: 0.9833 - 6ms/epoch - 1ms/step
Epoch 994/1000
4/4 - 0s - loss: 0.0503 - accuracy: 0.9833 - 11ms/epoch - 3ms/step
Epoch 995/1000
4/4 - 0s - loss: 0.0495 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 996/1000
4/4 - 0s - loss: 0.0501 - accuracy: 0.9833 - 7ms/epoch - 2ms/step
Epoch 997/1000
4/4 - 0s - loss: 0.0499 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 998/1000
4/4 - 0s - loss: 0.0514 - accuracy: 0.9833 - 8ms/epoch - 2ms/step
Epoch 999/1000
4/4 - 0s - loss: 0.0500 - accuracy: 0.9833 - 9ms/epoch - 2ms/step
Epoch 1000/1000
4/4 - 0s - loss: 0.0512 - accuracy: 0.9833 - 10ms/epoch - 2ms/step


In [12]:
results = model.evaluate(feature_test , target_test)
print("Accuracy : %.2f" % results[1])


1/1 [==============================] - 0s 117ms/step - loss: 0.0417 - accuracy: 0.9667
Accuracy : 0.97
